# Generated by Django 5.0.4 on 2024-11-19 14:55

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('etablissement_enseigne', models.CharField(max_length=400, null=True, verbose_name='Etablissement enseigné')),
                ('volume_horaire_statuaire', models.IntegerField(null=True, verbose_name='Volume horaire statuaire')),
                ('abattement', models.IntegerField(null=True, verbose_name="veuillez saisir l'abattement")),
                ('motif_abattement', models.CharField(max_length=400, null=True, verbose_name="Motif de l'abattement")),
                ('v_h_obli_apres_abattement', models.IntegerField(null=True, verbose_name='Volume horaire après abattement')),
                ('date_debut', models.DateField(verbose_name='Date de début du cours')),
                ('date_fin', models.DateField(verbose_name='Date de fin du cours')),
                ('is_validated', models.BooleanField(null=True, verbose_name='Validé')),
                ('motif_de_rejet', models.CharField(max_length=400, null=True, verbose_name='motif_refus')),
                ('is_permanent', models.BooleanField(null=True, verbose_name='type_fiche_permanent')),
                ('validate_by_responsable_filiere', models.BooleanField(null=True)),
                ('validate_by_responsable_ufr', models.BooleanField(null=True)),
                ('validate_by_vice_presient', models.BooleanField(null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_enseignant', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_filiere', to='parameter.filiere', verbose_name='Filière consernée')),
            ],
            options={
                'verbose_name': 'Fiche',
                'verbose_name_plural': 'Fiches',
                'ordering': ['-created'],
                'permissions': [('list_fiche', 'Peut lister Fiche'), ('can_valide_sheet', 'Peut valider Fiche'), ('can_invalide_sheet', 'Peut invalider Fiche'), ('can_add_multiple_sheet', 'Peut soumettre un formulaire pour enseignant Fiche')],
            },
        ),
        migrations.CreateModel(
            name='Enseignements',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, null=True, unique=True, verbose_name='code')),
                ('ct_volume_horaire_confie', models.IntegerField(verbose_name='Volume_horaire confié, CT')),
                ('td_volume_horaire_confie', models.IntegerField(verbose_name='Volume_horaire confié, TD')),
                ('tp_volume_horaire_confie', models.IntegerField(verbose_name='Volume_horaire confié, TP')),
                ('ct_volume_horaire_efectue', models.IntegerField(verbose_name='Volume horaire éffectué, CT')),
                ('td_volume_horaire_efectue', models.IntegerField(verbose_name='Volume horaire éffectué, TD')),
                ('tp_volume_horaire_efectue', models.IntegerField(verbose_name='Volume horaire éffectué, TP')),
                ('is_validated', models.BooleanField(null=True, verbose_name='Validé')),
                ('motif_de_rejet', models.CharField(max_length=400, null=True, verbose_name='motif_refus')),
                ('validate_by_responsable_filiere', models.BooleanField(null=True)),
                ('validate_by_responsable_ufr', models.BooleanField(null=True)),
                ('validate_by_vice_presient', models.BooleanField(null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_module', to='parameter.module', verbose_name='Module enseigné')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_niveau', to='parameter.niveau', verbose_name='Niveau de la filière')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_semestre', to='parameter.semestre', verbose_name='Semestre du cours')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignement_sheet', to='fiche_management.sheet')),
            ],
            options={
                'verbose_name': 'Enseignement',
                'verbose_name_plural': 'Enseignements',
                'ordering': ['-created'],
                'permissions': [('list_enseignement', 'Peut lister Enseignement')],
            },
        ),
    ]
