# Generated by Django 5.1.2 on 2024-10-30 22:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameter', '0002_departement_created_departement_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_debut', models.DateField(verbose_name='Date de début du cours')),
                ('date_fin', models.DateField(verbose_name='Date de fin du cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_enseignant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche',
                'verbose_name_plural': 'Fiches',
                'ordering': ['-created'],
                'permissions': [('list_fiche', 'Peut lister Fiche')],
            },
        ),
        migrations.CreateModel(
            name='enseignements',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('ct_volume_horaire_confie', models.IntegerField(verbose_name='Volume_horaire confié, CT')),
                ('td_volume_horaire_confie', models.IntegerField(verbose_name='Volume_horaire confié, TD')),
                ('tp_volume_horaire_confie', models.IntegerField(verbose_name='Volume_horaire confié, TP')),
                ('ct_volume_horaire_efectue', models.IntegerField(verbose_name='Volume horaire éffectué, CT')),
                ('td_volume_horaire_efectue', models.IntegerField(verbose_name='Volume horaire éffectué, TD')),
                ('tp_volume_horaire_efectue', models.IntegerField(verbose_name='Volume horaire éffectué, TP')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_filiere', to='parameter.filiere', verbose_name='Filière consernée')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_module', to='parameter.module', verbose_name='Module enseigné')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_niveau', to='parameter.niveau', verbose_name='Niveau de la filière')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_semestre', to='parameter.semestre', verbose_name='Semestre du cours')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignement_sheet', to='fiche_management.sheet')),
            ],
            options={
                'verbose_name': 'Enseignement',
                'verbose_name_plural': 'Enseignements',
                'ordering': ['-created'],
                'permissions': [('list_enseignement', 'Peut lister Enseignement')],
            },
        ),
    ]
