# Generated by Django 5.0.4 on 2024-11-30 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiche_management', '0001_initial'),
        ('parameter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_enseignant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sheet',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_filiere', to='parameter.filiere', verbose_name='Filière consernée'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='parameter.promotion', verbose_name='Année Universitaire'),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignement_sheet', to='fiche_management.sheet'),
        ),
    ]
