# Generated by Django 5.0.4 on 2024-11-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='validate_by_responsable_filiere',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='validate_by_responsable_ufr',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='validate_by_vice_presient',
            field=models.BooleanField(null=True),
        ),
    ]
