# Generated by Django 5.0.4 on 2025-02-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0002_initial'),
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='annee_univ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='parameter.annee_univ', verbose_name='Année Universitaire'),
        ),
    ]
