# Generated by Django 5.0.4 on 2024-11-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0002_enseignements_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_validated',
            field=models.BooleanField(null=True, verbose_name='Validé'),
        ),
    ]
