# Generated by Django 5.0.4 on 2024-11-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignements',
            name='is_validated',
            field=models.BooleanField(null=True, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='motif_de_rejet',
            field=models.CharField(max_length=400, null=True, verbose_name='motif_refus'),
        ),
    ]
