# Generated by Django 5.0.4 on 2024-11-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0002_initial'),
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='parameter.promotion', verbose_name='Année Universitaire'),
        ),
    ]
