# Generated by Django 5.0.4 on 2024-11-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0003_sheet_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='motif_de_rejet',
            field=models.CharField(max_length=400, null=True, verbose_name='motif_refus'),
        ),
    ]
