# Generated by Django 5.0.4 on 2024-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0003_alter_sheet_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date_debut',
            field=models.DateField(null=True, verbose_name='Date de début du cours'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date_fin',
            field=models.DateField(null=True, verbose_name='Date de fin du cours'),
        ),
    ]
