# Generated by Django 5.0.4 on 2024-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_management', '0004_alter_sheet_date_debut_alter_sheet_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignements',
            name='ct_volume_horaire_efectue',
            field=models.IntegerField(null=True, verbose_name='Volume horaire éffectué, CT'),
        ),
        migrations.AlterField(
            model_name='enseignements',
            name='td_volume_horaire_efectue',
            field=models.IntegerField(null=True, verbose_name='Volume horaire éffectué, TD'),
        ),
        migrations.AlterField(
            model_name='enseignements',
            name='tp_volume_horaire_efectue',
            field=models.IntegerField(null=True, verbose_name='Volume horaire éffectué, TP'),
        ),
    ]
