# Generated by Django 5.0.4 on 2024-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_nomination',
            field=models.DateField(max_length=100, verbose_name='Date de nomination'),
        ),
    ]
