# Generated by Django 5.0.4 on 2025-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etablissement_enseigne',
            field=models.CharField(max_length=400, null=True, verbose_name='Etablissement enseigné'),
        ),
    ]
