# Generated by Django 5.1.2 on 2024-10-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('list_user', 'Can list user'), ('can_assign', 'Peut attribuer un rôle'), ('deactivate_user', 'Can deactivate user'), ('change_right_user', 'Can change user right'), ('access_parameter', 'Can access to parameter module'), ('access_account', 'Can access to account module'), ('can_submit_programmatic_sheet', 'Peut soumettre une fiche programmatique'), ('can_update_programmatic_sheet', 'Peut modifier une fiche programmatique'), ('can_delete_programmatic_sheet', 'Peut supprimer une fiche programmatique'), ('can_download_programmatic_sheet', 'peut telecharger une fiche programmatique'), ('can_export_programmatic_sheet', 'Peut exporter une fiche programmatique'), ('can_validate_programmatic_sheet', 'peut valider une fiche programmatique'), ('can_reject_programmatic_sheet', 'peut rejeter une fiche programmatique')], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'ADMINISTRATEUR'), ('student', 'Etudiant'), ('teacher', 'Enseignant')], default='student', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
