# Generated by Django 5.0.4 on 2024-11-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0002_alter_user_options_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diplome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diplôme'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_type',
            field=models.CharField(blank=True, choices=[('vacataire', 'Vacataire'), ('permanent', 'Permanent')], help_text="Indiquez si l'enseignant est vacataire ou permanent", max_length=10, null=True, verbose_name="Type d'enseignant"),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('bachelor', 'Célibataire'), ('married', 'Mariée'), ('divorced', 'Divorcée'), ('widower', 'Veuve')], default='bachelor', max_length=20, verbose_name='Situation matrimoniale'),
        ),
    ]
