# Generated by Django 5.0.4 on 2024-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0002_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='is_desactivate',
            field=models.BooleanField(default=False, verbose_name='Est inactif'),
        ),
    ]
