# Generated by Django 5.0.4 on 2025-02-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0002_user_etablissement_enseigne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributmodule',
            old_name='enseignant',
            new_name='user',
        ),
    ]
