# Generated by Django 5.0.4 on 2025-02-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0003_rename_enseignant_attributmodule_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributmodule',
            options={'verbose_name': 'assignation de module', 'verbose_name_plural': 'attributions de modules'},
        ),
        migrations.RemoveField(
            model_name='attributmodule',
            name='filiere',
        ),
    ]
