# Generated by Django 5.0.4 on 2025-02-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
        ('xauth', '0004_alter_attributmodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='module',
            field=models.ManyToManyField(related_name='user_module', to='parameter.module', verbose_name='Modules attribués'),
        ),
    ]
