# Generated by Django 5.0.4 on 2024-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0004_nomination_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nomination_type',
            field=models.CharField(choices=[('filiere', 'Filière'), ('ufr', 'UFR'), ('vise-president', 'Vice-président')], max_length=20),
        ),
    ]
