# Generated by Django 5.1.2 on 2024-10-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['label'],
                'permissions': [('list_departement', 'Peut lister Département')],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['label'],
                'permissions': [('list_niveau', 'Peut lister Niveau')],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['label'],
                'permissions': [('list_semestre', 'Peut lister Semestre')],
            },
        ),
        migrations.CreateModel(
            name='UniteDeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Unité de Recherche',
                'verbose_name_plural': 'Unités de Recherche',
                'ordering': ['label'],
                'permissions': [('list_unitederecherche', 'Peut lister Unité de Recherche')],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_department', to='parameter.departement')),
                ('niveaux', models.ManyToManyField(related_name='filiere_niveaux', to='parameter.niveau')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['label'],
                'permissions': [('list_filiere', 'Peut lister Filière')],
            },
        ),
        migrations.AddField(
            model_name='niveau',
            name='semestres',
            field=models.ManyToManyField(related_name='filiere_semestres', to='parameter.semestre'),
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_filiere', to='parameter.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_niveau', to='parameter.niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_semestre', to='parameter.semestre')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['label'],
                'permissions': [('list_ue', "Peut lister Unité d'Enseignement")],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('volume_horaire', models.IntegerField(null=True, verbose_name='volume_horaire')),
                ('credit', models.IntegerField(null=True, verbose_name='credit')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_department', to='parameter.departement')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_filiere', to='parameter.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_niveau', to='parameter.niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_semestre', to='parameter.semestre')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.ue')),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_urf', to='parameter.unitederecherche')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['label'],
                'permissions': [('list_module', 'Peut lister module')],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement_urf', to='parameter.unitederecherche'),
        ),
    ]
