# Generated by Django 5.0.4 on 2025-01-14 21:54

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_univ',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Année universitaire')),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(verbose_name='Fin')),
            ],
            options={
                'verbose_name': 'annee_univ',
                'verbose_name_plural': 'annee_univs',
                'ordering': ['name'],
                'permissions': [('list_module', 'Peut lister annee_univ')],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['label'],
                'permissions': [('list_departement', 'Peut lister Département')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['label'],
                'permissions': [('list_Grade', 'Peut lister grade')],
            },
        ),
        migrations.CreateModel(
            name='MailContent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account_activation_mail', models.TextField(blank=True, default='{{phone}}\n{{link}}', null=True, verbose_name="Mail d'activation de compte avec lien")),
                ('account_activation_sms', models.TextField(blank=True, default='{{phone}}\n{{otp}}', null=True, verbose_name="Génération d'OTP pour activation d'un compte")),
            ],
            options={
                'verbose_name': 'contenu de mail',
                'verbose_name_plural': 'contenus de mail',
                'ordering': ['pk'],
                'permissions': [('list_mailcontent', 'peut lister contenu de mail')],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['label'],
                'permissions': [('list_niveau', 'Peut lister Niveau')],
            },
        ),
        migrations.CreateModel(
            name='UniteDeRecherche',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Unité de Recherche',
                'verbose_name_plural': 'Unités de Recherche',
                'ordering': ['label'],
                'permissions': [('list_unitederecherche', 'Peut lister Unité de Recherche')],
            },
        ),
        migrations.CreateModel(
            name='Volume_horaire',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('heures', models.PositiveIntegerField(verbose_name='Volume horaire (en heures)')),
            ],
            options={
                'verbose_name': 'volumeHoraire',
                'verbose_name_plural': 'volumeHoraires',
                'ordering': ['heures'],
                'permissions': [('list_volume_horaire', 'Peut lister volumeHoraire')],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_department', to='parameter.departement')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['label'],
                'permissions': [('list_filiere', 'Peut lister Filière')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nom de la promotion')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('filiere', models.ManyToManyField(related_name='promotion_filiere', to='parameter.filiere')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ['name'],
                'permissions': [('list_promotion', 'Peut lister promotion')],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestre_niveau', to='parameter.niveau')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['label'],
                'permissions': [('list_semestre', 'Peut lister Semestre')],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='parameter.departement', verbose_name='Département')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_filiere', to='parameter.filiere')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='parameter.niveau', verbose_name='Niveau')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='parameter.semestre', verbose_name='Semestre')),
                ('ufr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='parameter.unitederecherche', verbose_name='UFR')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['label'],
                'permissions': [('list_ue', "Peut lister Unité d'Enseignement")],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement_urf', to='parameter.unitederecherche'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('cours_theorique', models.IntegerField(default=0, verbose_name='Volume horaire cours théorique')),
                ('travaux_pratiques', models.IntegerField(default=0, verbose_name='Volume horaire travaux tratiques')),
                ('travaux_diriges', models.IntegerField(default=0, verbose_name='Volume horaire travaux dirigés')),
                ('credit', models.IntegerField(default=0, verbose_name='Crédit')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='parameter.departement', verbose_name='Département')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_filiere', to='parameter.filiere')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='parameter.niveau', verbose_name='Niveau')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='parameter.semestre', verbose_name='Semestre')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_filiere', to='parameter.ue')),
                ('ufr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='parameter.unitederecherche', verbose_name='UFR')),
                ('volume_horaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_volume_horaire', to='parameter.volume_horaire', verbose_name='Volume horaire')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['label'],
                'permissions': [('list_module', 'Peut lister module')],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('valeur', models.PositiveIntegerField(editable=False, verbose_name='Valeur du crédit')),
                ('volume_horaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='parameter.volume_horaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
