# Generated by Django 5.0.4 on 2024-11-21 14:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Sigle')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['label'],
                'permissions': [('list_departement', 'Peut lister Département')],
            },
        ),
        migrations.CreateModel(
            name='MailContent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account_activation_mail', models.TextField(blank=True, default='{{phone}}\n{{link}}', null=True, verbose_name="Mail d'activation de compte avec lien")),
                ('account_activation_sms', models.TextField(blank=True, default='{{phone}}\n{{otp}}', null=True, verbose_name="Génération d'OTP pour activation d'un compte")),
            ],
            options={
                'verbose_name': 'contenu de mail',
                'verbose_name_plural': 'contenus de mail',
                'ordering': ['pk'],
                'permissions': [('list_mailcontent', 'peut lister contenu de mail')],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Sigle')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['label'],
                'permissions': [('list_niveau', 'Peut lister Niveau')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nom de la promotion')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ['name'],
                'permissions': [('list_module', 'Peut lister promotion')],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Sigle')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['label'],
                'permissions': [('list_semestre', 'Peut lister Semestre')],
            },
        ),
        migrations.CreateModel(
            name='UniteDeRecherche',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Sigle')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Unité de Recherche',
                'verbose_name_plural': 'Unités de Recherche',
                'ordering': ['label'],
                'permissions': [('list_unitederecherche', 'Peut lister Unité de Recherche')],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Sigle')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_department', to='parameter.departement')),
                ('niveaux', models.ManyToManyField(related_name='filiere_niveaux', to='parameter.niveau')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['label'],
                'permissions': [('list_filiere', 'Peut lister Filière')],
            },
        ),
        migrations.AddField(
            model_name='niveau',
            name='semestres',
            field=models.ManyToManyField(related_name='filiere_semestres', to='parameter.semestre'),
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Sigle')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_filiere', to='parameter.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_niveau', to='parameter.niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_semestre', to='parameter.semestre')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['label'],
                'permissions': [('list_ue', "Peut lister Unité d'Enseignement")],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Sigle')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('volume_horaire', models.IntegerField(null=True, verbose_name='volume_horaire')),
                ('credit', models.IntegerField(null=True, verbose_name='credit')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_department', to='parameter.departement')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_filiere', to='parameter.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_niveau', to='parameter.niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_semestre', to='parameter.semestre')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.ue')),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_urf', to='parameter.unitederecherche')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['label'],
                'permissions': [('list_module', 'Peut lister module')],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement_urf', to='parameter.unitederecherche'),
        ),
    ]
