# Generated by Django 5.0.4 on 2024-11-01 19:27

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_departement_created_departement_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailContent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account_activation_mail', models.TextField(blank=True, default='{{phone}}\n{{link}}', null=True, verbose_name="Mail d'activation de compte avec lien")),
                ('account_activation_sms', models.TextField(blank=True, default='{{phone}}\n{{otp}}', null=True, verbose_name="Génération d'OTP pour activation d'un compte")),
                ('buy_sms', models.TextField(blank=True, default='{{phone}}\n{{otp}}', null=True, verbose_name="Génération d'OTP pour achat chez un marchand")),
                ('super_agent_for_activities', models.TextField(blank=True, default='{{transaction_type}}\n{{transaction_id}}', null=True, verbose_name="Rapport d'activités au super distributeur")),
            ],
            options={
                'verbose_name': 'contenu de mail',
                'verbose_name_plural': 'contenus de mail',
                'ordering': ['pk'],
                'permissions': [('list_mailcontent', 'peut lister contenu de mail')],
            },
        ),
    ]
