# Generated by Django 5.0.4 on 2024-11-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_mailcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailcontent',
            name='buy_sms',
        ),
        migrations.RemoveField(
            model_name='mailcontent',
            name='super_agent_for_activities',
        ),
    ]
